### ISSUE TITLE
Error in index.js

### ISSUE THREAD

**Issue by trashcatt** [mangosango/clive#17]
I'm getting an error when I try to start the script. 
System is a CentOS 7 VPS
Terminal output below

```
> clappybot@1.0.0 start /home/botuser/Clive
> nodemon src/index.js

/home/botuser/Clive/node_modules/chokidar/index.js:161
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/botuser/Clive/node_modules/nodemon/lib/monitor/watch.js:6:16)

npm ERR! Linux 3.10.0-1127.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! clappybot@1.0.0 start: `nodemon src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clappybot@1.0.0 start script 'nodemon src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the clappybot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs clappybot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls clappybot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/botuser/Clive/npm-debug.log
```

**Comment by jaredcat** [comment]
@trashcatt A lot of changes and fixes were just merged, so try it again!
Feel free to open a new issue if you run into any problems
